DELIMITER $$
DROP PROCEDURE IF EXISTS `getUserTypeByUserID`$$
CREATE PROCEDURE `getUserTypeByUserID`(IN USER_ID_VALUE INT(10) UNSIGNED)
BEGIN
	SELECT `type` FROM User_Type WHERE `user_id`=USER_ID_VALUE;
END$$